// ESM entry-point — mirrors src/index.js so Vite can import from
// @budget-app/shared without going through the CJS bundle.
// The API (Node.js) continues to use src/index.js via `require`.

export const POT_TYPES = {
  SPENDING: 'SPENDING',
  SAVING: 'SAVING',
  INVESTMENT: 'INVESTMENT',
};

export const LINE_ITEM_TYPES = {
  INSTANT_SPEND: 'INSTANT_SPEND',
  SINKING_FUND: 'SINKING_FUND',
};

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  EFT: 'EFT',
  OTHER: 'OTHER',
};

export const SPEND_LOG_TYPES = {
  INSTANT_SPEND: 'INSTANT_SPEND',
  SINKING_FUND_USED: 'SINKING_FUND_USED',
  SINKING_FUND_DEPOSIT: 'SINKING_FUND_DEPOSIT',
  SINKING_FUND_INTEREST: 'SINKING_FUND_INTEREST',
  TRANSFER_OUT: 'TRANSFER_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
};

export const ALERT_TYPES = {
  POT_APPROACHING_LIMIT: 'POT_APPROACHING_LIMIT',
  POT_OVER_BUDGET: 'POT_OVER_BUDGET',
  SINKING_FUND_READY: 'SINKING_FUND_READY',
  UNALLOCATED_INCOME: 'UNALLOCATED_INCOME',
  STALE_BUDGET: 'STALE_BUDGET',
  MONTH_READY_TO_LOCK: 'MONTH_READY_TO_LOCK',
  POT_LEFTOVER: 'POT_LEFTOVER',
  BILL_DUE: 'BILL_DUE',
  BILL_OVERDUE: 'BILL_OVERDUE',
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE: 'DUPLICATE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  MONTH_LOCKED: 'MONTH_LOCKED',
  ALREADY_LOCKED: 'ALREADY_LOCKED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  INCOME_BELOW_ALLOCATIONS: 'INCOME_BELOW_ALLOCATIONS',
  ALLOCATION_EXCEEDED: 'ALLOCATION_EXCEEDED',
  SINKING_FUND_FIELDS: 'SINKING_FUND_FIELDS',
  INVALID_FIELDS_FOR_TYPE: 'INVALID_FIELDS_FOR_TYPE',
  POT_HAS_HISTORY: 'POT_HAS_HISTORY',
  WRONG_TYPE: 'WRONG_TYPE',
  NOT_READY: 'NOT_READY',
  AMOUNT_EXCEEDS_BALANCE: 'AMOUNT_EXCEEDS_BALANCE',
  INVALID_TARGET_POT: 'INVALID_TARGET_POT',
  SAME_FUND: 'SAME_FUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
